algoritmo "biografia"
var
// seccao de declaracao de variaveis
    nome: caractere
    apelido: caractere
    diadenascimento: inteiro
    localdenascimento: caractere
    descricao: caractere
    mesdenascimento:caractere
    anodenascimento: inteiro
    javenceumundial :logico
inicio
// seccao de atribuicao de variaveis
       nome <- "Lionel"
       apelido <- "Messi"
       localdenascimento <- "Argentina"
       mesdenascimento <- "junho"
       diadenascimento <- 25
       anodenascimento <- 1987
       descricao <- "jogador argentino canhoto"
       javenceumundial <- verdadeiro
       
       // seccao de saida de dados
       escreval("nome - ", nome)
       escreval("apelido - ",apelido)
       escreval("mes de nascimento - ", mesdenascimento)
       escreval("local - ",localdenascimento)
       escreval("dia de nascimento - ",diadenascimento)
       escreval("ano de nascimento - ",anodenascimento)
       escreval("descricao - ",descricao)
       escreval("ja venceu um mudial - ",javenceumundial)
fimalgoritmo

